Post http://localhost:5000/breakfasts
Content-Type: application/json

{
    "name": "G",
    "description": "Ths",
    "startDateTime": "2023-02-17T08:00:00",
    "endDateTime": "2023-02-17T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Fruit"
    ]

}

###
GET https://localhost:5001/Breakfasts/0ae7fc9e-882d-4e4c-9b51-c086fc877310

}

