@id=893095a4-b0d9-4d81-9db4-ca2fa109f7dc
PUT  http://localhost:5000/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Its now dinner time",
    "description": "This breakfast contains nutrients",
    "startDateTime": "2023-02-17T08:00:00",
    "endDateTime": "2023-02-17T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Fruit"
    ]
}